# Generated by Django 5.0.7 on 2024-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='age',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='concert_attendance',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='device_preference',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='listening_hours_per_week',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='instrument',
            field=models.CharField(default='Guitarra eléctrica', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='language',
            field=models.CharField(default='Inglés', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='listening_platform',
            field=models.CharField(default='Spotify', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='listening_scenario',
            field=models.CharField(default='En casa, relajado/a', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='lyrics',
            field=models.CharField(default='Letras de amor y relaciones', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='musical_personality',
            field=models.CharField(default='Me encanta la energía y la adrenalina de la música', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='production_quality',
            field=models.CharField(default='Muy importante', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rhythm',
            field=models.CharField(default='Rápido y enérgico', max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='favorite_artist',
            field=models.CharField(default='The Beatles', max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='favorite_genre',
            field=models.CharField(default='Rock', max_length=50),
        ),
    ]
